#!/bin/csh -f
#******************************************************************************
#
#	    COPYRIGHT (c) 1988, 1998 by Globetrotter Software Inc.
#	This software has been provided pursuant to a License Agreement
#	containing restrictions on its use.  This software contains
#	valuable trade secrets and proprietary information of 
#	Globetrotter Software Inc and is protected by law.  It may 
#	not be copied or distributed in any form or medium, disclosed 
#	to third parties, reverse engineered or used in any manner not 
#	provided for in said License Agreement except with the prior 
#	written authorization from Globetrotter Software Inc.
#
#	Module:	BINARY_CLEAN v3.18.0.0
#	Last changed:  11/12/96
#******************************************************************************
#
#	Clean up stuff that doesn't belong on binary kits
#

#
#	Stuff that doesn't belong
#
set nonomatch
#rm -f lmlite
#make clean

#
#	End binary kit cleanup
#
