cd app
mkdir intel_rel
mkdir intel_debug
mkdir alpha_rel
cd ..\src
mkdir sintel_rel
mkdir sintel_debug
mkdir intel_rel
mkdir dsintel_rel
mkdir alpha_rel
mkdir dsalpha_rel
mkdir salpha_rel
cd ..\master
mkdir sintel_rel
mkdir sintel_debug
cd ..\server
mkdir intel_rel
mkdir intel_debug
mkdir alpha_rel
cd ..\test
mkdir sintel_rel
mkdir sintel_debug
mkdir salpha_rel
cd ..\utils
mkdir sintel_rel
mkdir sintel_debug
mkdir salpha_rel
cd ..\vendor
mkdir sintel_rel
mkdir sintel_debug
mkdir salpha_rel
cd ..\testsuite
mkdir sintel_rel
mkdir sintel_debug
mkdir salpha_rel
cd ..
mkdir i86_n3
