/****************************************************************************
*
* (C) Unpublished Copyright Novell, Inc. All Rights Reserved.
*
* No part of this file may be duplicated, revised, translated,
* localized or modified in any manner or compiled, linked or 
* uploaded or downloaded to or from any computer system without
* the prior written consent of Novell, Inc.
*
* NetWare C NLM Runtime Library source code
*
*****************************************************************************/

#ifndef _SYS_FILIO_H_INCLUDED

#define  FIONREAD    1  /* get # bytes to read */
#define  FIONBIO     2  /* set/clear non-blocking i/o */
#define  FIOGETNBIO  3  /* get non-blocking i/o status */

#define _SYS_FILIO_H_INCLUDED
#endif  /* _SYS_FILIO_H_INCLUDED */
