/******************************************************************************

	    COPYRIGHT (c) 1988, 2003 by Macrovision Inc.
	This software has been provided pursuant to a License Agreement
	containing restrictions on its use.  This software contains
	valuable trade secrets and proprietary information of 
	Macrovision Inc and is protected by law.  It may 
	not be copied or distributed in any form or medium, disclosed 
	to third parties, reverse engineered or used in any manner not 
	provided for in said License Agreement except with the prior 
	written authorization from Macrovision Inc.

/*****************************************************************************/
/*	
 *	Module:	$Id: lmlite.c,v 1.5 2003/01/14 21:47:21 kmaclean Exp $
 *
 *	Description:	This is a sample application to illustrate 
 *			the use of FLEXlm-ultralite
 *
 *	Last changed:  12/03/2002
 * 		Updated to work with licenses generated by lmcrypt 8.3
 * 		use 'lmcrypt -verfmt 6'  to generate a license that works here
 * 
 * 		Also set
 * 			#define LM_STRENGTH LM_STRENGTH_LICENSE_KEY
 * 		in lm_code.h
 *
 */
#include "lmseeds.h"
#include "lmachdep.h"
#include "lmprikey.h"
#include "lm_code.h"

int * l_prikey_sign(void) { return 0; }

#define FEATURE "f1"
#define GOODKEY_ANY "E65A383BD96F" 
 
#define HOSTID2 "12345678"
#define GOODKEY2 "9C9A82E2C3BC"

#define HOSTID3 "12345678a"
#define HOSTID3_ALT "12345678A"
#define GOODKEY3 "28D90A6D0B99"

#define BADRESULT  { badresults++; printf("***ERROR***\n\n"); }

LM_CODE(code, ENCRYPTION_SEED1, ENCRYPTION_SEED2, VENDOR_KEY1,
	VENDOR_KEY2, VENDOR_KEY3, VENDOR_KEY4, VENDOR_KEY5);

/* lc_checkit() needs to use the global scratch buffer named flexlm_data.
 * The client application is expected to allocate the memory.
 * 
 * lc_checkit() function does not expect the data in this buffer to be 
 * preserved; the application can free or reuse this buffer 
 * between calls to lc_checkit() */
char *flexlm_data;


main()
{
	char feature[MAX_FEATURE_LEN+1];
	int err;
	int i, j;
	int badresults = 0;
	char badkey[20];
	char data[LM_ULTRALITE_STATIC_SIZE];

	flexlm_data = data;
	LM_CODE_GEN_INIT(&code);

	/****************************************************************

	lc_checkit() takes 5 parameters:

	  	vendor name (char *)
	  	feature name (char *)
	  	license key (char *)
	  	licensed hostid (char *)
	  	VENDORCODE struct (LM_CODE *)

	There are 3 possible return values:

	  		    	0	Everything OK (license good, correct host)
	  	LM_BADFILE     -2	No hostid specified
	  	LM_BADCODE     -8	Bad license key
	  	LM_BADPARAM	   -42  Missing feature name or LM_CODE struct

	****************************************************************/

	(void) strcpy(feature, FEATURE);
	/*
	 *	Try the checkout with a few errors, then with a good license
	 */
	err = lc_checkit(VENDOR_NAME, "", GOODKEY_ANY, "", &code);
	printf("With no feature name, error is %d\n", err);
	if (err != LM_BADPARAM) BADRESULT

	err = lc_checkit(VENDOR_NAME, feature, GOODKEY_ANY, "", &code);
	printf("With no hostid, error is %d\n", err);
	if (err != LM_BADFILE) BADRESULT

	err = lc_checkit(VENDOR_NAME, feature, "", "12345", &code);
	printf("With no license key, error is %d\n", err);
	if (err != LM_BADCODE) BADRESULT

	err = lc_checkit(VENDOR_NAME, feature, GOODKEY_ANY, "12345", &code);
	printf("With bad hostid, error is %d\n", err);
	if (err != LM_BADCODE) BADRESULT

	printf("checking bad license keys (160 possiblities)...\n");
	for (j=0; j<10; j++)
	{
		if (j == 0) strcpy(badkey, "0");
		else if (j == 1) strcpy(badkey, "01");
		else if (j == 2) strcpy(badkey, "031");
		else if (j == 3) strcpy(badkey, "0a52");
		else if (j == 4) strcpy(badkey, "079ce");
		else if (j == 5) strcpy(badkey, "012345");
		else if (j == 6) strcpy(badkey, "0abcdef");
		else if (j == 7) strcpy(badkey, "09283745");
		else if (j == 8) strcpy(badkey, "0a00dfe12");
		else if (j == 9) strcpy(badkey, "0102938475");
		for (i=0; i<10; i++)
		{
			err = lc_checkit(VENDOR_NAME, feature, badkey, "ANY", &code);
			if (err != LM_BADCODE) 
			{
				BADRESULT
				printf("With bad license key (%s), error is %d\n", 
									badkey, err);
			}
			badkey[0]++;
		}
		badkey[0] = 'A';
		for (i=0; i<6; i++)
		{
			err = lc_checkit(VENDOR_NAME, feature, badkey, "ANY", &code);
			if (err != LM_BADCODE) 
			{
				BADRESULT
				printf("With bad license key (%s), error is %d\n", 
									badkey, err);
			}
			badkey[0]++;
	    }
	}
	err = lc_checkit(VENDOR_NAME, feature, GOODKEY_ANY, "ANY", &code);
	printf("With ANY hostid and license key, error is %d\n", err);
	if (err) BADRESULT

	err = lc_checkit(VENDOR_NAME, feature, GOODKEY2, HOSTID2, &code);
	printf("With good license key for 12345678, error is %d\n", err);
	if (err) BADRESULT

	err = lc_checkit(VENDOR_NAME, feature, GOODKEY3, HOSTID3, &code);
	printf("With good license key for 12345678a, error is %d\n", err);
	if (err) BADRESULT

	err = lc_checkit(VENDOR_NAME, feature, GOODKEY3, HOSTID3_ALT, &code);
	printf("With good license key for 12345678A, error is %d\n", err);
	if (err) BADRESULT

	if (badresults) printf("\n\n******	%d BAD result%s\n", badresults,
				badresults > 1 ? "s" : "");
	else		printf("\n\n******	ALL results GOOD\n");
}
